namespace: infisical

frontend:
  replicaCount: 1
  image:
    repository: 
    pullPolicy: IfNotPresent
    tag: "latest"

backend:
  replicaCount: 1
  image:
    repository: 
    pullPolicy: IfNotPresent
    tag: "latest"

ingress:
  enabled: false
  annotations: []
  hostName: example.com
  tls: {}

secrets:
  PRIVATE_KEY: REQUIRED
  PUBLIC_KEY: REQUIRED
  ENCRYPTION_KEY: REQUIRED
  JWT_SIGNUP_SECRET: REQUIRED
  JWT_REFRESH_SECRET: REQUIRED
  JWT_AUTH_SECRET: REQUIRED
  NODE_ENV: development
  SMTP_HOST: REQUIRED
  SMTP_NAME: REQUIRED
  SMTP_USERNAME: REQUIRED
  SMTP_PASSWORD: REQUIRED
  MONGO_URL: REQUIRED
    