#####
# INFISICAL K8 DEFAULT VALUES FIL
# PLEASE REPLACE VALUES/EDIT AS REQUIRED 
#####

nameOverride: ""

frontend:
  name: frontend
  replicaCount: 1
  image:
    repository: infisical/frontend
    pullPolicy: IfNotPresent
    tag: "latest"
    # kubeSecretRef: some-kube-secret-name
  service:
    # type of the frontend service
    type: ClusterIP
    # define the nodePort if service type is NodePort
    # nodePort: 

backend:
  name: backend
  replicaCount: 1
  image:
    repository: infisical/backend
    pullPolicy: IfNotPresent
    tag: "latest"
    # kubeSecretRef: some-kube-secret-name

mongodb:
  name: mongodb
  image:
    repository: mongo
    pullPolicy: IfNotPresent
    tag: "latest"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hostName: example.com
  frontend: 
    path: /
    pathType: Prefix
  backend:
    path: /api
    pathType: Prefix
  tls: []

## Complete Ingress example 
# ingress:
#   enabled: true
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     cert-manager.io/issuer: letsencrypt-nginx
#   hostName: k8.infisical.com
#   frontend: 
#     path: /
#     pathType: Prefix
#   backend:
#     path: /api
#     pathType: Prefix
#   tls:
#     - secretName: letsencrypt-nginx
#       hosts:
#         - k8.infisical.com

###
### YOU MUST FILL IN ALL SECRETS BELOW
### 
backendEnvironmentVariables:
  # Required keys for platform encryption/decryption ops. Replace with nacl sk keys
  ENCRYPTION_KEY: MUST_REPLACE

  # JWT
  # Required secrets to sign JWT tokens
  JWT_SIGNUP_SECRET: MUST_REPLACE
  JWT_REFRESH_SECRET: MUST_REPLACE
  JWT_AUTH_SECRET: MUST_REPLACE

  # Mail/SMTP
  # Required to send emails
  SMTP_HOST: MUST_REPLACE 
  SMTP_NAME: MUST_REPLACE
  SMTP_USERNAME: MUST_REPLACE
  SMTP_PASSWORD: MUST_REPLACE

  # Recommended to replace with Mongo Cloud URI as the DB instance in the cluster does not have persistence yet
  MONGO_URL: mongodb://root:root@mongodb-service:27017/

# frontendEnvironmentVariables:
    