apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infisical.backend.fullname" . }}
  labels:
    {{- include "infisical.backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "infisical.backend.matchLabels" . | nindent 6 }}
  template:
    metadata: 
      labels:
        {{- include "infisical.backend.matchLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ template "infisical.name" . }}-{{ .Values.backend.name }}
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports: 
        - containerPort: 4000
        {{- if .Values.backend.kubeSecretRef }}
        envFrom:
        - secretRef:
            name: {{ .Values.backend.kubeSecretRef }}
        {{- end }}
        env:
        {{- range $key, $value := .Values.backendEnvironmentVariables }}
        {{- if $value | quote | eq "MUST_REPLACE" }}
          {{ fail "Environment variables are not set. Please set all environment variables to continue." }}
        {{ end }}
        - name: {{ $key }}
          value: {{ quote $value }}
        {{- end }}

---
apiVersion: v1
kind: Service 
metadata:
  name: {{ include "infisical.backend.fullname" . }}
  labels:
    {{- include "infisical.backend.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "infisical.backend.matchLabels" . | nindent 8 }}
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000 # container port 
