apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend-deployment
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata: 
      labels:
        app: frontend 
    spec:
      containers:
      - name: frontend 
        image: infisical/frontend
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        {{- if .Values.frontend.kubeSecretRef }}
        envFrom:
        - secretRef:
            name: {{ .Values.frontend.kubeSecretRef }}
        {{- end }}
        {{- if .Values.frontendEnvironmentVariables }}
        env:
        {{- range $key, $value := .Values.frontendEnvironmentVariables }}
        {{- if $value | quote | eq "MUST_REPLACE" }}
          {{ fail "Environment variables are not set. Please set all environment variables to continue." }}
        {{ end }}
        - name: {{ $key }}
          value: {{ quote $value }}
        {{- end }}
        {{- end }}
        ports: 
        - containerPort: 4000
---
apiVersion: v1
kind: Service 
metadata:
  name: infisical-frontend-service 
spec:
  selector:
    app: frontend 
  ports:
    - protocol: TCP
      port: 3000 # service
      targetPort: 3000 # container port 
