apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-sample
spec:
  hostAPI: http://localhost:7070/api
  tokenSecretReference:
    secretName: service-token
    secretNamespace: default
  authentication:
    serviceAccount:
      serviceAccountSecretReference:
        secretName: service-account
        secretNamespace: default
      projectId: "6439ec224cfbf7ea2a95b651"
      environmentName: "dev"
  managedSecretReference:
    secretName: managed-secret
    secretNamespace: default
