name: Release Helm Charts

on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: Build helm package
        run: cd helm-charts && helm package ./infisical
        uses: helm/chart-releaser-action@v1.4.1
      - name: Install python and Cloudsmith CLI
        uses: actions/setup-python@v4
        run: pip install --upgrade cloudsmith-cli
      - name: Push helm package to Cloudsmith
        run: cd helm-charts && sh upload-to-cloudsmith.sh
        env:
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}