name: Release Docker image for K8 operator 
on: [workflow_dispatch]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 🔧 Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 🐋 Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: k8-operator
          push: true
          platforms: linux/amd64,linux/arm64
          tags: infisical/kubernetes-operator:latest

      - uses: actions/setup-go@v2

      - name: Generate YAML for Kubectl
        run: make dist charts

      - name: Upload CRD manifest
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/install-secrets-operator.yaml
          tag: ${{ github.ref }}